### PR TITLE
fix(export): using `vim.fn.expand` for path (fixes #540)

### LINKED ISSUE #540: Unable to export markdown when filename starts with "~"
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.2

### Neorg setup

    require('neorg').setup {
        load = {
            ["core.defaults"] = {},
            ["core.norg.dirman"] = {
                config = {
                    workspaces = {
                        work = "~/Documents/Notes/work",
                        home = "~/Documents/Notes/home",
                    }
                }
            },
            ["core.norg.concealer"] = {},
            ["core.norg.completion"] = {
                config = {
                    engine = "nvim-cmp"
                }
            },
            ["core.export"] = {
                config = {}
            },
            ["core.export.markdown"] = {
                config = {
                    extensions = "all"
                }
            }
        }
    }

### Actual behavior

`:Neorg export to-file /Users/doodleEsc/index.norg` works fine

`:Neorg export to-file ~/index.norg` does not work, and the error message is: "Failed to open file '~/index.md' for export: ENOENT: no such file or directory: ~/index.md"

### Expected behavior

both "/User/doodleEsc/index.md" and "~/index.md" works

### Steps to reproduce

:Neorg export to-file ~/index.norg

### Potentially conflicting plugins

_No response_

### Other information

_No response_

### Help

Yes

### Implementation help

_No response_

### PR DESCRIPTION
**Pull request by danilshvalov**
This patch fixes issue #540

### CODE REVIEW

File: lua/neorg/modules/core/export/module.lua [hunk 1]
```diff
@@ -210,26 +210,27 @@ module.on_event = function(event)
...
-                    neorg.lib.lazy_string_concat("Failed to write to file '", event.content[1], "' for export: ", werr)
+                    neorg.lib.lazy_string_concat("Failed to write to file '", filepath, "' for export: ", werr)
                 )
             end)
 
             vim.schedule(neorg.lib.wrap(vim.notify, "Successfully exported 1 file!"))
         end)
     elseif event.type == "core.neorgcmd.events.export.directory" then
-        local path = event.content[3]
+        local path = vim.fn.expand(event.content[3])
```
Comment (vhyrro) [inline lua/neorg/modules/core/export/module.lua:233]:
```suggestion
        local path = event.content[3] and vim.fn.expand(event.content[3])
```
The original version is a logic bug, as `event.content[3]` might be `nil`, in which case `vim.fn.expand()` will fail. Other than that the PR looks good :)
