### PR TITLE
fix(summary): Fix #1624

### LINKED ISSUE #1624: Neorg generate-workspace-summary causes an error
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.10.2

### Neorg setup

```lua
  1   {                                                                                                                                                                                                 
  2     "nvim-neorg/neorg",                                                                                                                                                                             
  3     opts = {                                                                                                                                                                                        
  4       load = {                                                                                                                                                                                      
  5         ["core.defaults"] = {},                                                                                                                                                                     
  6         -- ["core.dirman"] = {                                                                                                                                                                      
  7         --  config = {                                                                                                                                                                              
  8         --    workspaces = {                                                                                                                                                                        
  9         --      notes = "~/notes/general",                                                                                                                                                          
 10         --      aidev = "~/notes/aidev",                                                                                                                                                            
 11         --      example_gtd = "~/notes/gtd",                                                                                                                                                        
 12         --    },                                                                                                                                                                                    
 13         --    default_workspace = "notes",                                                                                                                                                          
 14         --  },                                                                                                                                                                                      
 15         -- },                                                                                                                                                                                       
 16         -- -- ["core.integrations.nvim-cmp"] = {},                                                                                                                                                  
 17         -- ["core.completion"] = {                                                                                                                                                                  
 18         --  config = {                                                                                                                                                                              
 19         --    engine = "nvim-cmp",                                                                                                                                                                  
 20         --  },                                                                                                                                                                                      
 21         -- },                                                                                                                                                                                       
 22         -- ["core.concealer"] = {                                                                                                                                                                   
 23         --  config = {                                                                                                                                                                              
 24         --    folds = false,                                                                                                                                                                        
 25         --  },                                                                                                                                                                                      
 26         -- },                                                                                                                                                                                       
 27         -- ["core.integrations.image"] = {},                                                                                                                                                        
 28         -- ["core.latex.renderer"] = {},                                                                                                                                                            
 29         -- ["core.export"] = {},                                                                                                                                                                    
 30         ["core.summary"] = {},                                                                                                                                                                      
 31       },                                                                                                                                                                                            
 32     },                                                                                                                                                                                              
 33   },                                                                                                                                                                                                
```

### Actual behavior

Generated error when trying to generate summary:

image

```
Error executing Lua callback: vim/shared.lua:0: bad argument #1 to '?' (string expected, got table)
stack traceback:
    [builtin#81]: at 0x0105211810
    vim/shared.lua: in function 'tbl_map'
    ...vim/lazy/neorg/lua/neorg/modules/core/summary/module.lua:344: in function 'generate_workspace_summary'
    ...vim/lazy/neorg/lua/neorg/modules/core/summary/module.lua:366: in function 'on_event'
    .../local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:822: in function 'broadcast_event'
    ...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:301: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:206>
```

### Expected behavior

A summary of the workspace should be inserted into the file

### Steps to reproduce

`:Neorg workspace notes`
`:Neorg generate-workspace-summary`

### Potentially conflicting plugins

_No response_

### Other information

_No response_

### Help

No

### Implementation help

_No response_

### PR DESCRIPTION
**Pull request by OmegaLambda1998**
Extract category / path args from generate_workspace_summary command. Tested with both strategies and it seems to work.

### CODE REVIEW

**Comment by OmegaLambda1998** [comment]
Looks like there's an alternative solution (#1640) happy for this to be closed if that version is preferred.

**Comment by benlubas** [comment]
Yeah this doesn't work I don't think. `tab:unpack(2)` will skip the first category in the list.

that's not to mention that table.unpack doesn't even exist in neovim's lua version. it's still just `unpack`

That said. I much prefer this approach to the other one. It's a lot simpler

File: lua/neorg/modules/core/summary/module.lua [hunk 1]
```diff
@@ -363,7 +363,11 @@ module.events.subscribed = {
 
 module.on_event = function(event)
     if event.type == "core.neorgcmd.events.summary.summarize" then
-        module.public.generate_workspace_summary(event.buffer, event.cursor_position, event.content)
+	-- Extract any additional arguments past the first
+	-- So that :Neorg generate_workspace_summary a b c
+	-- Will result in include_categories = {"a", "b", "c"}
+	local include_categories = {table.unpack(event.content.data.fargs, 2)}
+        module.public.generate_workspace_summary(event.buffer, event.cursor_position, include_categories)
```
Comment (benlubas) [inline lua/neorg/modules/core/summary/module.lua]:
```suggestion
        -- Remove `data` key, and take only the numerical keys from event.content
        -- these numerical keys are the category args passed to the command
        local include_categories = { unpack(event.content) }
        module.public.generate_workspace_summary(event.buffer, event.cursor_position, include_categories)
```

**Comment by OmegaLambda1998** [comment]
So from my testing calling `generate_workspace_summary a b c` will set `fargs` to `{generate_workspace_summary, a, b, c}`, hence why I was skipping the first element of fargs. This also means that if you just call `generate_workspace_summary` with no categories, this will result in an empty list.

I've updated `table.unpack -> unpack` apologies for that I had `table.unpack = table.unpack or unpack` earlier in my nvim config.

**Review by benlubas — CHANGES_REQUESTED** [review]
There were a few things wrong with this so I've fixed them, I like this approach better than the other one. please review and format if necessary. Thanks

**Comment by benlubas** [comment]
My bad, I didn't notice that you were using fargs. That works, but there's no reason to do that. What do you think of the solution that I've suggested?

File: lua/neorg/modules/core/summary/module.lua [hunk 2]
```diff
@@ -363,7 +363,11 @@ module.events.subscribed = {
 
 module.on_event = function(event)
     if event.type == "core.neorgcmd.events.summary.summarize" then
-        module.public.generate_workspace_summary(event.buffer, event.cursor_position, event.content)
+	-- Extract any additional arguments past the first
+	-- So that :Neorg generate_workspace_summary a b c
+	-- Will result in include_categories = {"a", "b", "c"}
+	local include_categories = {unpack(event.content)}
+        module.public.generate_workspace_summary(event.buffer, event.cursor_position, include_categories)
```
Comment (benlubas) [inline lua/neorg/modules/core/summary/module.lua:370]: Let's just apply this suggestion so the comment is more accurate and the formatting matches the rest of the repo!

```suggestion
        -- Remove `data` key, and take only the numerical keys from event.content
        -- these numerical keys are the category args passed to the command
        local include_categories = { unpack(event.content) }
        module.public.generate_workspace_summary(event.buffer, event.cursor_position, include_categories)
```

**Review by benlubas — APPROVED** [review]

**Comment by benlubas** [comment]
Thank you!
